[package]
name = "actix-microservice"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
diesel = {version="*", features=["mysql"]}
dotenv = "0.15.0"
serde = "1"
serde_json = "1"
